# Generated by Django 5.1.6 on 2025-02-28 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('vendedores', '0002_remove_vendedor_comissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriocomissao',
            name='total_comissao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='relatoriocomissao',
            name='total_vendas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='relatoriocomissao',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='vendedores.vendedor'),
        ),
    ]
