# Generated by Django 5.2.11 on 2026-02-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='taxa_aplicada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taxa (%) aplicada no momento do registro. Imutável após criação.', max_digits=5, null=True),
        ),
    ]
