# Generated by Django 5.1.6 on 2025-02-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_venda_valor_comissao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['-data_venda'], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
    ]
