# Generated by Django 5.2.11 on 2026-02-26 19:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendedores', '0002_vendedor_taxa_comissao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_CONFERENCIA', 'Em Conferência'), ('ENVIADA', 'Enviada para Contabilidade'), ('APROVADA', 'Aprovada para Pagamento'), ('PAGA', 'Paga')], default='ABERTA', max_length=20)),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('aprovada_em', models.DateTimeField(blank=True, null=True)),
                ('paga_em', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('aprovada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencias_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('enviada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencias_enviadas', to=settings.AUTH_USER_MODEL)),
                ('paga_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencias_pagas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('ano', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_padrao', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Taxa padrão de comissão (%) quando não há configuração específica.', max_digits=5)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Comissão',
                'verbose_name_plural': 'Configuração de Comissão',
            },
        ),
        migrations.CreateModel(
            name='FaixaComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor mínimo de vendas no mês (inclusive).', max_digits=12)),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, help_text='Valor máximo (inclusive). Vazio = sem limite.', max_digits=12, null=True)),
                ('taxa', models.DecimalField(decimal_places=2, help_text='Taxa de comissão (%) para esta faixa.', max_digits=5)),
                ('vendedor', models.ForeignKey(blank=True, help_text='Vazio = faixa global aplicável a todos.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faixas_comissao', to='vendedores.vendedor')),
            ],
            options={
                'verbose_name': 'Faixa de Comissão',
                'verbose_name_plural': 'Faixas de Comissão',
                'ordering': ['vendedor', 'valor_minimo'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoTaxaComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_anterior', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taxa_nova', models.DecimalField(decimal_places=2, max_digits=5)),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, default='', max_length=500)),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(blank=True, help_text='Vazio = alteração na taxa global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico_taxas', to='vendedores.vendedor')),
            ],
            options={
                'verbose_name': 'Histórico de Taxa',
                'verbose_name_plural': 'Histórico de Taxas',
                'ordering': ['-alterado_em'],
            },
        ),
        migrations.CreateModel(
            name='ComissaoVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_vendas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_comissao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ajustes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('comissao_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='vendedores.vendedor')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_vendedores', to='comissoes.competencia')),
            ],
            options={
                'verbose_name': 'Comissão por Vendedor',
                'verbose_name_plural': 'Comissões por Vendedor',
                'ordering': ['vendedor__nome'],
                'unique_together': {('vendedor', 'competencia')},
            },
        ),
    ]
