# Generated by Django 5.1.6 on 2025-02-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='comissao',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='percentual_comissao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
