# Generated by Django 5.2.11 on 2026-02-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='taxa_comissao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taxa individual (%). Se vazio, usa taxa padrão ou faixas.', max_digits=5, null=True),
        ),
    ]
