# Generated by Django 5.1.6 on 2025-02-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0002_remove_vendedor_comissao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='percentual_comissao',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='cpf',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
