# Generated by Django 5.1.6 on 2025-02-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0003_remove_vendedor_percentual_comissao_vendedor_cpf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
    ]
